repos:
  - repo: https://github.com/FHPythonUtils/Blackt
    rev: '2022.0.3'
    hooks:
      - id: blackt

  - repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/pylint
    rev: v2.15.9
    hooks:
      - id: pylint
        exclude: "tests/"
        args: [--disable=import-error,--jobs=0]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: "tests/"
      - id: end-of-file-fixer
        exclude: "tests/"

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/boidolr/pre-commit-images
    rev: v1.1.0
    hooks:
      - id: optimize-avif
        exclude: "tests/"
      - id: optimize-jpg
        exclude: "tests/"
      - id: optimize-png
        exclude: "tests/"
      - id: optimize-svg
        exclude: "tests/"
      - id: optimize-webp
        exclude: "tests/"
